### ISSUE TITLE
Adapt to GraalVM changes by adding new distributions?

### ISSUE THREAD

**Issue by lread** [sdkman/sdkman-disco-integration#12]
Hiya!

The discoapi just added new graal distributions to adapt to the fact that:
1. in addition to the community edition, there is now an Oracle GraalVM release (also free but under a different license)
2. versioning now matches JDK versioning scheme for both distributions

So the discoapi now has new distros:
- `graalvm` for new Oracle GraalVM, example: https://api.foojay.io/disco/v3.0/packages?distro=graalvm
- `graalvm_community` for community edition with new version scheme, example: https://api.foojay.io/disco/v3.0/packages?distro=graalvm_community

And preserves existing legacy `graalvm_ce*` distributions. Example: https://api.foojay.io/disco/v3.0/packages?distro=graalvm_ce19

For some details see: https://github.com/foojayio/discoapi/issues/75

**Comment by eddumelendez** [comment]
Thanks for the offer but there is still some work to be done in the backend in order to support the new distributions

**Comment by lread** [comment]
Ah I see, thanks for the reply, and lemme know if I can be of any help!

**Comment by eddumelendez** [comment]
This commits add support for new GraalVM https://github.com/sdkman/sdkman-disco-integration/commit/a8d2a09c9b61c707ba5918bf1df35166ebe09453

You can find them available in sdkman

<img width="754" alt="Screenshot 2023-06-24 at 16 03 35" src="https://github.com/sdkman/sdkman-disco-integration/assets/1810547/fa84ba97-d452-4e0b-90cf-0b3cf4956bbd">

**Comment by lread** [comment]
Thanks so much @eddumelendez!
