### ISSUE TITLE
LibericaJDK 21 with fx is not available in sdkman

### ISSUE THREAD

**Issue by strizhik** [sdkman/sdkman-disco-integration#14]
Hello,

LibericaJDK 21 Full (with FX) is not in sdkman. The latest version with FX is 20.0.2
```
 sdk  list java
 ....
  Liberica      |     | 21           | librca  |            | 21-librca
                |     | 20.0.2.fx    | librca  |            | 20.0.2.fx-librca
```

Foojay API correctly provides packages with new version:

https://api.foojay.io/disco/v3.0/packages?package_type=jdk&latest=available&version=21&javafx_bundled=true&distribution=liberica&operating_system=linux

Could you please take a look?

Thanks!

**Comment by eddumelendez** [comment]
it should be there already
