### ISSUE TITLE
Open JDK 23 GA is not showing

### ISSUE THREAD

**Issue by jvissers** [sdkman/sdkman-disco-integration#24]
Trying to get Open JDK 23 GA, but it is not showing when I do `sdk list java`. This is the list I currently see:

![image](https://github.com/user-attachments/assets/828d24ca-6fe2-4ec4-9066-d07d443cb47c)

**Comment by jvissers** [comment]
Following this on [SO](https://stackoverflow.com/questions/55809928/sdkman-is-missing-a-specific-java-version), what you can do is something like:

1. Download the desired JDK version, e.g. `wget https://download.java.net/java/GA/jdk23/3c5b90190c68498b986a97f276efd28a/37/GPL/openjdk-23_linux-x64_bin.tar.gz`
2. Go to the sdkman candidates directory, e.g. `cd ~/.sdkman/candidates/java`
3. Unpack the download tar.gz file, e.g. `tar -xvzf /tmp/openjdk-23_linux-x64_bin.tar.gz`
4. Rename the directory, e.g. `mv jdk-23 23-open`

After that `sdk list java` will show:
![image](https://github.com/user-attachments/assets/dfde8e67-a44f-4455-9a0b-47772f5688de)

Unless I'm missing something, to me this seems like a work around, as really the Open JDK 23 version should be available from sdk proper.

**Comment by eddumelendez** [comment]
Hi, it is available now.
