### ISSUE TITLE
GraalVM CE 22.2.0 picked up?

### ISSUE THREAD

**Issue by lread** [sdkman/sdkman-disco-integration#3]
Thanks for all this cool automation!

Curious, Is Oracle GraalVM CE being automatically picked up?

I see something called "Gluon GraalVM" in the README but not Oracle GraalVM.

**Comment by eddumelendez** [comment]
sorry for the delay. There was an issue from the API we fetch all versions but it is fixed now and graalvm is available via sdkman.

**Comment by lread** [comment]
> sorry for the delay

Oh no problem at all, and thank you so much for doing all this awesomeness!
